${EE_SIDE_PREFIX}_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    update_rate: 1000
    joints:
      - ${EE_SIDE_PREFIX}_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    open_loop_control: true

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 5.0
      ${EE_SIDE_PREFIX}_finger_joint:
        goal: 0.02
